/*INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1101,'MASS BRIGHAM GENERAL HOSPITAL','243 CHARLES STREET','BOSTON','02114',4146772234,'ACH12345HOSP');

INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1102,'ILLINOIS GENERAL HOSPITAL','1310 COMMONS DRIVE','CHICAGO','60134',3124433567,'ILL3425HOSP');

INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1103,'SOUTHERN CALIFORNIA HOSPITAL','6245 DE LONGPRE AVE','LOS ANGELES','90015',6167090808,'LAG2908HOSP');

INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1104,'GWU HOSPITAL','900 23RD STREET','WASHINGTON DC','20037',7178907070,'WAS7178HOSP'); 

--Select * from All_ROLE_PRIVS 
--Where GRANTEE = 'HOSPITAL_ADMIN';





SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE DEL_RECIPIENT(I_RECIPIENT_ID IN RECIPIENT.RECIPIENT_ID%TYPE) AS

BEGIN
	DELETE FROM REGISTRATION
	WHERE RECIPIENT_ID = I_RECIPIENT_ID;
	
	DELETE FROM RECIPIENT
	WHERE RECIPIENT_ID = I_RECIPIENT_ID;

	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT RECIPIENT_ID ' || I_RECIPIENT_ID || ' SUCESSFULLY DELETED ');

END;

/
CREATE OR REPLACE PROCEDURE DEL_REGISTRATION(I_REGISTRATION_ID IN REGISTRATION.REGISTRATION_ID%TYPE) AS

BEGIN
	DELETE FROM VACCINE_RECORD
	WHERE REGISTRATION_ID = I_REGISTRATION_ID;
	
	DELETE FROM REGISTRATION
	WHERE REGISTRATION_ID = I_REGISTRATION_ID;

	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT REGISTRATION_ID ' || I_REGISTRATION_ID || ' SUCESSFULLY DELETED ');

END;

/

CREATE OR REPLACE PROCEDURE DEL_VACCINE_RECORD(I_VACCINE_RECORD_ID IN VACCINE_RECORD.VACCINE_RECORD_ID%TYPE) AS

BEGIN
	DELETE FROM VACCINE_RECORD
	WHERE VACCINE_RECORD_ID = I_VACCINE_RECORD_ID;

	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT VACCINE_RECORD_ID ' || I_VACCINE_RECORD_ID || ' SUCESSFULLY DELETED ');

END;
/

CREATE OR REPLACE PROCEDURE DEL_VACCINE_DETAILS(I_VACCINE_ID IN VACCINE_DETAILS.VACCINE_ID%TYPE) AS

BEGIN
	DELETE FROM VACCINE_RECORD
	WHERE VACCINE_ID = I_VACCINE_ID;

	DELETE FROM VACCINE_DETAILS
	WHERE VACCINE_ID = I_VACCINE_ID;
	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT REGISTRATION_ID ' || I_VACCINE_ID || ' SUCESSFULLY DELETED ');

END;

/
CREATE OR REPLACE PROCEDURE DEL_MEDICAL_WORKER(I_MEDICAL_WORKER_ID IN MEDICAL_WORKER.MEDICAL_WORKER_ID%TYPE) AS

BEGIN
	DELETE FROM VACCINE_RECORD
	WHERE MEDICAL_WORKER_ID = I_MEDICAL_WORKER_ID;

	DELETE FROM MEDICAL_WORKER
	WHERE MEDICAL_WORKER_ID = I_MEDICAL_WORKER_ID;
	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT MEDICAL_WORKER_ID ' || I_MEDICAL_WORKER_ID || ' SUCESSFULLY DELETED ');

END;

/
CREATE OR REPLACE PROCEDURE DEL_HOSPITAL(I_HOSPITAL_ID IN HOSPITAL.HOSPITAL_ID%TYPE) AS

BEGIN
	DELETE FROM MEDICAL_WORKER
	WHERE HOSPITAL_ID = I_HOSPITAL_ID;

	DELETE FROM HOSPITAL
	WHERE HOSPITAL_ID = I_HOSPITAL_ID;
	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT HOSPITAL_ID ' || I_HOSPITAL_ID || ' SUCESSFULLY DELETED ');

END;
/
*/

SET SERVEROUTPUT ON;
EXECUTE PKG_DELETE_RECORDS_RECIEPIENT.DEL_REGISTRATION(50020);
EXECUTE PKG_DELETE_RECORDS_HOSPITAL_ADMIN.DEL_MEDICAL_WORKER(12013);
EXECUTE PKG_DELETE_RECORDS_APP_ADMIN.DEL_VACCINE_DETAILS(304);
EXECUTE PKG_DELETE_RECORDS_APP_ADMIN.DEL_HOSPITAL(1104);
EXECUTE PKG_DELETE_RECORDS_APP_ADMIN.DEL_RECIPIENT(108);
EXECUTE PKG_DELETE_MEDICAL_WORKER.DEL_VACCINE_RECORD(60121);

SELECT * FROM all_users;
GRANT EXECUTE ON PKG_DELETE_RECORDS_HOSPITAL_ADMIN TO HOSPITAL_ADMIN;
GRANT EXECUTE ON PKG_DELETE_MEDICAL_WORKER TO MEDICAL_WORKER;
GRANT EXECUTE ON PKG_DELETE_RECORDS_RECIEPIENT TO RECIPIENT;
