CREATE OR REPLACE PACKAGE PKG_DELETE_MEDICAL_WORKER AS 

  PROCEDURE DEL_VACCINE_RECORD(I_VACCINE_RECORD_ID IN VACCINE_RECORD.VACCINE_RECORD_ID%TYPE); 

END PKG_DELETE_MEDICAL_WORKER;
/


CREATE OR REPLACE PACKAGE BODY PKG_DELETE_MEDICAL_WORKER AS

  PROCEDURE DEL_VACCINE_RECORD(I_VACCINE_RECORD_ID IN VACCINE_RECORD.VACCINE_RECORD_ID%TYPE) AS 
  UNQID NUMBER;
  INVALID_INPUTS EXCEPTION;
  
  BEGIN
  SELECT COUNT(*) INTO UNQID FROM VACCINE_RECORD
    WHERE VACCINE_RECORD_ID = I_VACCINE_RECORD_ID;
    IF (UNQID < 1)
    THEN 
        RAISE INVALID_INPUTS;
    END IF;
  
    DELETE FROM VACCINE_RECORD
	WHERE VACCINE_RECORD_ID = I_VACCINE_RECORD_ID;


	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT VACCINE_RECORD_ID ' || I_VACCINE_RECORD_ID || ' SUCESSFULLY DELETED ');
    
    COMMIT;
    
    EXCEPTION
    WHEN INVALID_INPUTS
    THEN 
    dbms_output.put_line('DETAILS ABOUT VACCINE_RECORD_ID ' || I_VACCINE_RECORD_ID || ' NOT FOUND ');
  END DEL_VACCINE_RECORD;

END PKG_DELETE_MEDICAL_WORKER;
/
