CREATE OR REPLACE PACKAGE PKG_DELETE_RECORDS_APP_ADMIN AS 

  PROCEDURE DEL_RECIPIENT(I_RECIPIENT_ID IN RECIPIENT.RECIPIENT_ID%TYPE);
  PROCEDURE DEL_HOSPITAL(I_HOSPITAL_ID IN HOSPITAL.HOSPITAL_ID%TYPE);
  PROCEDURE DEL_VACCINE_DETAILS(I_VACCINE_ID IN VACCINE_DETAILS.VACCINE_ID%TYPE);

END PKG_DELETE_RECORDS_APP_ADMIN;
/


CREATE OR REPLACE PACKAGE BODY PKG_DELETE_RECORDS_APP_ADMIN AS

  PROCEDURE DEL_RECIPIENT(I_RECIPIENT_ID IN RECIPIENT.RECIPIENT_ID%TYPE) AS
  UNQIDR NUMBER;
  INVALID_INPUTS_RECIPIENT EXCEPTION;
  BEGIN
  SELECT COUNT(*) INTO UNQIDR FROM RECIPIENT
    WHERE RECIPIENT_ID = I_RECIPIENT_ID;
    IF (UNQIDR < 1)
    THEN 
        RAISE INVALID_INPUTS_RECIPIENT;
    END IF;
    
    DELETE FROM REGISTRATION
	WHERE RECIPIENT_ID = I_RECIPIENT_ID;
	
	DELETE FROM RECIPIENT
	WHERE RECIPIENT_ID = I_RECIPIENT_ID;

	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT RECIPIENT_ID ' || I_RECIPIENT_ID || ' SUCESSFULLY DELETED ');
    
    COMMIT;
    
    EXCEPTION
    WHEN INVALID_INPUTS_RECIPIENT
    THEN 
    dbms_output.put_line('DETAILS ABOUT RECIPIENT_ID ' || I_RECIPIENT_ID || ' NOT FOUND ');
    
  END DEL_RECIPIENT;

  PROCEDURE DEL_HOSPITAL(I_HOSPITAL_ID IN HOSPITAL.HOSPITAL_ID%TYPE) AS
  UNQIDH NUMBER;
  INVALID_INPUTS_HOSPITAL EXCEPTION;
  BEGIN
  SELECT COUNT(*) INTO UNQIDH FROM HOSPITAL
    WHERE HOSPITAL_ID = I_HOSPITAL_ID;
    IF (UNQIDH < 1)
    THEN 
        RAISE INVALID_INPUTS_HOSPITAL;
    END IF;
    
    DELETE FROM MEDICAL_WORKER
	WHERE HOSPITAL_ID = I_HOSPITAL_ID;

	DELETE FROM HOSPITAL
	WHERE HOSPITAL_ID = I_HOSPITAL_ID;
	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT HOSPITAL_ID ' || I_HOSPITAL_ID || ' SUCESSFULLY DELETED ');
    
    COMMIT;
    
    EXCEPTION
    WHEN INVALID_INPUTS_HOSPITAL
    THEN 
    dbms_output.put_line('DETAILS ABOUT HOSPITAL_ID ' || I_HOSPITAL_ID || ' NOT FOUND ');
    
  END DEL_HOSPITAL;

  PROCEDURE DEL_VACCINE_DETAILS(I_VACCINE_ID IN VACCINE_DETAILS.VACCINE_ID%TYPE) AS
  UNQIDV NUMBER;
  INVALID_INPUTS_VACCINE EXCEPTION;
  BEGIN
  SELECT COUNT(*) INTO UNQIDV FROM VACCINE_DETAILS
    WHERE VACCINE_ID = I_VACCINE_ID;
    IF (UNQIDV < 1)
    THEN 
        RAISE INVALID_INPUTS_VACCINE;
    END IF;
    
    DELETE FROM VACCINE_RECORD
	WHERE VACCINE_ID = I_VACCINE_ID;

	DELETE FROM VACCINE_DETAILS
	WHERE VACCINE_ID = I_VACCINE_ID;
	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT VACCINE_ID ' || I_VACCINE_ID || ' SUCESSFULLY DELETED ');
    
    COMMIT;
    
    EXCEPTION
    WHEN INVALID_INPUTS_VACCINE
    THEN 
    dbms_output.put_line('DETAILS ABOUT VACCINE_ID ' || I_VACCINE_ID || ' NOT FOUND ');

  END DEL_VACCINE_DETAILS;

END PKG_DELETE_RECORDS_APP_ADMIN;
/
