CREATE OR REPLACE PACKAGE PKG_DELETE_RECORDS_RECIEPIENT AS 

  PROCEDURE DEL_REGISTRATION(I_REGISTRATION_ID IN REGISTRATION.REGISTRATION_ID%TYPE); 

END PKG_DELETE_RECORDS_RECIEPIENT;
/


CREATE OR REPLACE PACKAGE BODY PKG_DELETE_RECORDS_RECIEPIENT AS

  PROCEDURE DEL_REGISTRATION(I_REGISTRATION_ID IN REGISTRATION.REGISTRATION_ID%TYPE) AS
  UNQID NUMBER;
  INVALID_INPUTS EXCEPTION;
  BEGIN
    SELECT COUNT(*) INTO UNQID FROM REGISTRATION
    WHERE REGISTRATION_ID = I_REGISTRATION_ID;
    IF (UNQID < 1)
    THEN 
        RAISE INVALID_INPUTS;
    END IF;
  
    DELETE FROM VACCINE_RECORD
	WHERE REGISTRATION_ID = I_REGISTRATION_ID;
	
	DELETE FROM REGISTRATION
	WHERE REGISTRATION_ID = I_REGISTRATION_ID;

	
	DBMS_OUTPUT.PUT_LINE('DETAILS ABOUT REGISTRATION_ID ' || I_REGISTRATION_ID || ' SUCESSFULLY DELETED ');
    
    COMMIT;
    
    EXCEPTION
    WHEN INVALID_INPUTS
    THEN 
    dbms_output.put_line('DETAILS ABOUT REGISTRATION_ID ' || I_REGISTRATION_ID || ' NOT FOUND ');

  END DEL_REGISTRATION;

END PKG_DELETE_RECORDS_RECIEPIENT;
/
