CREATE OR REPLACE PACKAGE PKG_ONBOARD AS 

PROCEDURE ONBOARD_RECIPIENT 
(IN_RECIPIENT_ID IN NUMBER, 
IN_FIRST_NAME IN VARCHAR2,
IN_LAST_NAME IN VARCHAR2, 
IN_DATE_OF_BIRTH IN DATE, 
IN_CONTACT_NUMBER IN NUMBER,
IN_STREET_ADDRESS IN VARCHAR2, 
IN_CITY IN VARCHAR2, 
IN_ZIPCODE IN VARCHAR2, 
IN_GENDER IN VARCHAR2
);

PROCEDURE ONBOARD_VACCINE_DETAILS 
(IN_VACCINE_ID IN NUMBER, 
IN_VACCINE_NAME IN VARCHAR2,
IN_VIAL_SIZE IN NUMBER,  
IN_LOT_ID IN VARCHAR2,
IN_MANUFACTURED_DATE IN DATE, 
IN_EXPIRY_DATE IN DATE
);

PROCEDURE ONBOARD_HOSPITAL
(IN_HOSPITAL_ID IN NUMBER, 
IN_HOSPITAL_NAME IN VARCHAR2,
IN_HOSPITAL_STREET_ADDRESS IN VARCHAR2, 
IN_CITY IN VARCHAR2, 
IN_ZIPCODE IN VARCHAR2,
IN_HOSPITAL_CONTACT IN NUMBER, 
IN_HOSPITAL_LICENSE_NUMBER IN VARCHAR2
);


END PKG_ONBOARD;
/


CREATE OR REPLACE PACKAGE BODY PKG_ONBOARD AS
PROCEDURE ONBOARD_RECIPIENT 
(
  IN_RECIPIENT_ID IN NUMBER,
  IN_FIRST_NAME IN VARCHAR2, 
  IN_LAST_NAME IN VARCHAR2, 
  IN_DATE_OF_BIRTH IN DATE, 
 IN_CONTACT_NUMBER IN NUMBER,
 IN_STREET_ADDRESS IN VARCHAR2, 
 IN_CITY IN VARCHAR2, 
 IN_ZIPCODE IN VARCHAR2, 
 IN_GENDER IN VARCHAR2 
) AS 
 INVALID_INPUTS EXCEPTION;


BEGIN


IF
(in_recipient_id <= 0
OR LENGTH(IN_FIRST_NAME)<=0
OR LENGTH(IN_LAST_NAME)<=0
OR IN_DATE_OF_BIRTH is NULL
OR IN_CONTACT_NUMBER<=0
OR LENGTH(IN_STREET_ADDRESS)<=0
OR LENGTH(IN_CITY)<=0
OR LENGTH(IN_ZIPCODE)<=0
OR LENGTH(IN_GENDER)<=0)
THEN 
    RAISE INVALID_INPUTS;
END IF;

  INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES (IN_RECIPIENT_ID, IN_FIRST_NAME, IN_LAST_NAME, IN_DATE_OF_BIRTH,IN_CONTACT_NUMBER,IN_STREET_ADDRESS,IN_CITY,IN_ZIPCODE,
IN_GENDER);

COMMIT;
    
EXCEPTION
WHEN INVALID_INPUTS
THEN 
dbms_output.put_line('Invalid input');

END ONBOARD_RECIPIENT;

PROCEDURE ONBOARD_VACCINE_DETAILS 
(IN_VACCINE_ID IN NUMBER, 
IN_VACCINE_NAME IN VARCHAR2,
IN_VIAL_SIZE IN NUMBER,  
IN_LOT_ID IN VARCHAR2,
IN_MANUFACTURED_DATE IN DATE, 
IN_EXPIRY_DATE IN DATE
) AS 
 INVALID_INPUTS EXCEPTION;


BEGIN


IF
(IN_VACCINE_ID <=0
OR LENGTH(IN_VACCINE_NAME)<=0
OR IN_VIAL_SIZE <=0
OR IN_MANUFACTURED_DATE is NULL
OR IN_EXPIRY_DATE is NULL
OR LENGTH(IN_LOT_ID)<=0) 
THEN 
    RAISE INVALID_INPUTS;
END IF;

  INSERT INTO VACCINE_DETAILS(VACCINE_ID, VACCINE_NAME, VIAL_SIZE, LOT_ID, MANUFACTURED_DATE, EXPIRY_DATE)
VALUES (IN_VACCINE_ID,IN_VACCINE_NAME, IN_VIAL_SIZE, IN_LOT_ID,IN_MANUFACTURED_DATE,IN_EXPIRY_DATE);

COMMIT;
    
EXCEPTION
WHEN INVALID_INPUTS
THEN 
dbms_output.put_line('Invalid input');

END ONBOARD_VACCINE_DETAILS;

--hospital
PROCEDURE ONBOARD_HOSPITAL
(IN_HOSPITAL_ID IN NUMBER, 
IN_HOSPITAL_NAME IN VARCHAR2,
IN_HOSPITAL_STREET_ADDRESS IN VARCHAR2, 
IN_CITY IN VARCHAR2, 
IN_ZIPCODE IN VARCHAR2,
IN_HOSPITAL_CONTACT IN NUMBER, 
IN_HOSPITAL_LICENSE_NUMBER IN VARCHAR2
) AS 
 INVALID_INPUTS EXCEPTION;

BEGIN

IF
IN_HOSPITAL_ID IS NULL
OR LENGTH(IN_HOSPITAL_NAME)<=0
OR LENGTH(IN_HOSPITAL_STREET_ADDRESS)<=0
OR LENGTH(IN_CITY)<=0
OR LENGTH(IN_ZIPCODE)<=0
OR IN_HOSPITAL_CONTACT <=0
OR LENGTH(IN_HOSPITAL_LICENSE_NUMBER)<=0
THEN 
    RAISE INVALID_INPUTS;
END IF;

  INSERT INTO hospital(HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER)
VALUES (IN_HOSPITAL_ID,IN_HOSPITAL_NAME,IN_HOSPITAL_STREET_ADDRESS,IN_CITY,IN_ZIPCODE,IN_HOSPITAL_CONTACT, IN_HOSPITAL_LICENSE_NUMBER);

COMMIT;
    
EXCEPTION
WHEN INVALID_INPUTS
THEN 
dbms_output.put_line('Invalid input');

END ONBOARD_HOSPITAL;

END PKG_ONBOARD;
/
