CREATE OR REPLACE PACKAGE PKG_ONBOARD_MEDICAL_WORKER AS 

PROCEDURE ONBOARD_MEDICAL_WORKER
(IN_MEDICAL_WORKER_ID IN NUMBER, 
IN_FIRST_NAME IN VARCHAR2,
IN_LAST_NAME IN VARCHAR2, 
IN_CONTACT_NUMBER IN NUMBER, 
IN_STREET_ADDRESS IN VARCHAR2,
IN_CITY IN VARCHAR2,
IN_ZIPCODE IN VARCHAR2,
IN_GENDER IN VARCHAR2,
IN_EMAIL_ID IN VARCHAR2,
IN_HOSPITAL_ID IN NUMBER
);

END PKG_ONBOARD_MEDICAL_WORKER;
/


CREATE OR REPLACE PACKAGE BODY PKG_ONBOARD_MEDICAL_WORKER AS

  PROCEDURE ONBOARD_MEDICAL_WORKER
(IN_MEDICAL_WORKER_ID IN NUMBER, 
IN_FIRST_NAME IN VARCHAR2,
IN_LAST_NAME IN VARCHAR2, 
IN_CONTACT_NUMBER IN NUMBER, 
IN_STREET_ADDRESS IN VARCHAR2,
IN_CITY IN VARCHAR2,
IN_ZIPCODE IN VARCHAR2,
IN_GENDER IN VARCHAR2,
IN_EMAIL_ID IN VARCHAR2,
IN_HOSPITAL_ID IN NUMBER
) AS
INVALID_INPUTS EXCEPTION;

BEGIN
   IF
IN_MEDICAL_WORKER_ID <= 0
OR LENGTH(IN_FIRST_NAME)<= 0
OR LENGTH(IN_LAST_NAME)<= 0
OR IN_CONTACT_NUMBER <= 0
OR LENGTH(IN_STREET_ADDRESS)<= 0
OR LENGTH(IN_CITY)<=0
OR LENGTH(IN_ZIPCODE)<=0
OR LENGTH(IN_GENDER)<=0
OR LENGTH(IN_EMAIL_ID)<=0
OR IN_HOSPITAL_ID <= 0

THEN 
    RAISE INVALID_INPUTS;
END IF;

  INSERT INTO MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER,EMAIL_ID,HOSPITAL_ID)
VALUES (IN_MEDICAL_WORKER_ID,IN_FIRST_NAME,IN_LAST_NAME,IN_CONTACT_NUMBER,IN_STREET_ADDRESS,IN_CITY,IN_ZIPCODE,IN_GENDER,IN_EMAIL_ID,IN_HOSPITAL_ID);

COMMIT;
    
EXCEPTION
WHEN INVALID_INPUTS
THEN 
dbms_output.put_line('Invalid input');
    
    
END ONBOARD_MEDICAL_WORKER;

END PKG_ONBOARD_MEDICAL_WORKER;
/
