CREATE OR REPLACE PACKAGE PKG_ONBOARD_VACCINE_REC AS 

PROCEDURE ONBOARD_VACCINE_REC
(IN_VACCINE_REC_ID IN NUMBER, 
IN_START_TIME IN TIMESTAMP,
IN_END_TIME IN TIMESTAMP, 
IN_VACCINE_RECORD_DATE IN DATE, 
IN_REMARKS IN VARCHAR2,
IN_F_MEDICAL_WORKER_ID IN NUMBER, 
IN_F_REGISTRATION_ID IN NUMBER,
IN_F_VACCINE_ID IN NUMBER
); 

END PKG_ONBOARD_VACCINE_REC;
/


CREATE OR REPLACE PACKAGE BODY PKG_ONBOARD_VACCINE_REC AS

  PROCEDURE ONBOARD_VACCINE_REC
(IN_VACCINE_REC_ID IN NUMBER, 
IN_START_TIME IN TIMESTAMP,
IN_END_TIME IN TIMESTAMP, 
IN_VACCINE_RECORD_DATE IN DATE, 
IN_REMARKS IN VARCHAR2,
IN_F_MEDICAL_WORKER_ID IN NUMBER, 
IN_F_REGISTRATION_ID IN NUMBER,
IN_F_VACCINE_ID IN NUMBER
) AS

INVALID_INPUTS EXCEPTION;

BEGIN
   IF
IN_VACCINE_REC_ID <= 0
OR IN_START_TIME IS NULL
OR IN_END_TIME IS NULL
OR IN_VACCINE_RECORD_DATE IS NULL
OR LENGTH(IN_REMARKS)<= 0
OR IN_F_MEDICAL_WORKER_ID <= 0
OR IN_F_REGISTRATION_ID <= 0
OR IN_F_VACCINE_ID <= 0

THEN 
    RAISE INVALID_INPUTS;
END IF;

  INSERT INTO VACCINE_RECORD(VACCINE_RECORD_ID,START_TIME,END_TIME,VACCINE_RECORD_DATE,REMARKS,MEDICAL_WORKER_ID,REGISTRATION_ID,VACCINE_ID)
VALUES (IN_VACCINE_REC_ID,IN_START_TIME,IN_END_TIME,IN_VACCINE_RECORD_DATE,IN_REMARKS,IN_F_MEDICAL_WORKER_ID,IN_F_REGISTRATION_ID,IN_F_VACCINE_ID);

COMMIT;
    
EXCEPTION
WHEN INVALID_INPUTS
THEN 
dbms_output.put_line('Invalid input');


  END ONBOARD_VACCINE_REC;

END PKG_ONBOARD_VACCINE_REC;
/
