CREATE OR REPLACE TRIGGER ELIGIBILITYVALIDATION 
BEFORE INSERT ON RECIPIENT 
FOR EACH ROW
BEGIN
    IF 
        MONTHS_BETWEEN(SYSDATE,:NEW.DATE_OF_BIRTH) < 12*12 THEN :NEW.AGE_ELIGIBILITY := 'NOT ELIGIBLE';
    ELSE 
        :NEW.AGE_ELIGIBILITY := 'ELIGIBLE';
    END IF;
END;