create or replace TRIGGER LASTVACCINECHECK 
BEFORE INSERT OR UPDATE ON REGISTRATION 
FOR EACH ROW
BEGIN
  IF ((CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) - DATE'1970-01-01') * 86400 - date_to_unix_ts(:NEW.last_vaccination_date)) < 15552000 THEN raise_application_error(-20001,'VACCINE GAP SHOULD BE 180 DAYS AND ABOVE');
  END IF;
END;