SET SERVEROUTPUT ON;
--EXECUTE PROCEDURE FOR LOGIN CHECK
--VALID LOGIN
EXECUTE APP_ADMIN.LOGIN_CHECK('gray.ellen','AVatar@i345'); 
--INVALID LOGIN
EXECUTE APP_ADMIN.LOGIN_CHECK('mithal','Switzerland@2022'); 

--EXECUTE VACCINE PRICE FUNCTION
SELECT APP_ADMIN.GET_VAXX_PRICE('COVAXIN') AS VACCINE_PRICE FROM DUAL;
SELECT APP_ADMIN.GET_VAXX_PRICE('JJ') AS VACCINE_PRICE FROM DUAL;
