CREATE OR REPLACE FUNCTION CALCULATEEFFICACY 
(
  vacc_id NUMBER 
) 
RETURN VARCHAR2 IS efficacy VARCHAR2(999);
BEGIN
    SELECT
        concat((SUM(CASE WHEN VACCINE_RECORD.REMARKS = 'NULL' THEN 1 ELSE 0 END)/COUNT(VACCINE_RECORD.REMARKS))*100, '%') into efficacy
        FROM VACCINE_RECORD  
        where
        VACCINE_ID = vacc_id;
        RETURN efficacy;
END CALCULATEEFFICACY;


