--------------------------------------------------------
--  File created - Tuesday-December-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure LOGIN_CHECK
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "APP_ADMIN"."LOGIN_CHECK" 
(USER_IN IN REGISTRATION.USERNAME%TYPE, 
 PASS_IN IN REGISTRATION.PASS_WORD%TYPE)
AS
PASS_USER REGISTRATION.PASS_WORD%TYPE;
USER_ID NUMBER;
VALID_LOGIN EXCEPTION;
INVALID_LOGIN EXCEPTION;

BEGIN
SELECT COUNT(*) INTO USER_ID FROM REGISTRATION
WHERE USERNAME = USER_IN;
IF (USER_ID > 0)
THEN
SELECT PASS_WORD INTO PASS_USER FROM REGISTRATION
WHERE USERNAME = USER_IN;
IF (PASS_USER = PASS_IN)
THEN
RAISE VALID_LOGIN;
ELSE
RAISE INVALID_LOGIN;
END IF;
ELSE
RAISE INVALID_LOGIN;
END IF;

EXCEPTION
WHEN INVALID_LOGIN
THEN 
DBMS_OUTPUT.PUT_LINE('INVALID LOGIN');
WHEN VALID_LOGIN
THEN
DBMS_OUTPUT.PUT_LINE('VALID LOGIN');

END LOGIN_CHECK;

/

  GRANT EXECUTE ON "APP_ADMIN"."LOGIN_CHECK" TO "RECIPIENT";
  GRANT DEBUG ON "APP_ADMIN"."LOGIN_CHECK" TO "RECIPIENT";
