INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12011,'JOHN','GLOVER',6172344342,'225 HUNTINGTON AVE','BOSTON','02115',1101,'MALE','g.john@gmail.com');

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12012,'FIONA','DALTON',8769971678,'3760 ARCHER ROAD','WASHINGTON DC','20030',1104,'FEMALE','d.fio@gmail.com');

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12013,'DAMIEN','LAURENT',5678902341,'245 CLEMENT STREET','SPRINGFIELD','60124',1102,'MALE','ian.rent@gmail.com'); 

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12014,'LAURA','WELLING',4145897654,'22 CONECTICUT AVE','SOMERVILLE','02144',1101,'OTHER','wellslaura@gmail.com'); 

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12015,'ANA','COUNSELOS',3137890915,'5200 HOLLYWOOD BVLD','LOS ANGELES','90027',1103,'FEMALE','counselos.ana@gmail.com');

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12016,'ELLIOT','GONZALEZ',7128907654,'4426 CARNABY STREET','SPOKANE','99203',1104,'OTHER','gonzalezell@gmail.com');

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12017,'BRIANA','SCOTT',8137126708,'4600 WEST 65TH STREET','CHICAGO','60629',1102,'FEMALE','briscott@gmail.com');

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12018,'JUAN','DSILVA',6132897654,'884 BURTON GROVE','LOS ANGELES','90048',1103,'MALE','juan.dsilva@gmail.com');

 


INSERT INTO APP_ADMIN.MEDICAL_WORKER(MEDICAL_WORKER_ID,FIRST_NAME,LAST_NAME,CONTACT_NUMBER,STREET_ADDRESS, 
CITY,ZIPCODE,HOSPITAL_ID,GENDER,EMAIL_ID) 
VALUES 
(12019,'ANIKA','SMITH',8576432190,'40 HARRIET AVENUE','QUINCY','02171',1101,'OTHER','anikaquincy@gmail.com'); 