--User and Access
CREATE USER APP_ADMIN IDENTIFIED BY Datadojo2022;
CREATE USER HOSPITAL_ADMIN IDENTIFIED BY Datadojo2022;
CREATE USER MEDICAL_WORKER IDENTIFIED BY Datadojo2022;
CREATE USER RECIPIENT IDENTIFIED BY Datadojo2022;

GRANT CONNECT,RESOURCE TO APP_ADMIN;
GRANT CONNECT,RESOURCE TO HOSPITAL_ADMIN;
GRANT CONNECT,RESOURCE TO MEDICAL_WORKER;
GRANT CONNECT,RESOURCE TO RECIPIENT;

ALTER USER APP_ADMIN QUOTA UNLIMITED ON DATA;

ALTER USER HOSPITAL_ADMIN QUOTA 250M ON DATA;

ALTER USER MEDICAL_WORKER QUOTA 250M ON DATA;

ALTER USER RECIPIENT QUOTA 250M ON DATA;

GRANT CREATE ANY VIEW TO APP_ADMIN;
