SET SERVEROUTPUT ON;
declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='VACCINE_RECORD';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE VACCINE_RECORD';
    END IF;
END;
/

declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='REGISTRATION';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE REGISTRATION';
    END IF;
END;
/

declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='MEDICAL_WORKER';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE MEDICAL_WORKER';
    END IF;
END;
/

declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='VACCINE_DETAILS';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE VACCINE_DETAILS';
    END IF;
END;
/

declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='HOSPITAL';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE HOSPITAL';
    END IF;
END;
/


declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='RECIPIENT';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE RECIPIENT';
    END IF;
END;
/

declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from user_tables where table_name='AUDIT_LOG';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG';
    END IF;
END;
/

CREATE TABLE RECIPIENT(
RECIPIENT_ID NUMBER CONSTRAINT RECIPIENT_PK PRIMARY KEY,
FIRST_NAME VARCHAR(90),
LAST_NAME VARCHAR(90),
DATE_OF_BIRTH DATE NOT NULL,
CONTACT_NUMBER NUMBER NOT NULL CONSTRAINT CONTACT_RECIPIENT_UNQ UNIQUE,
STREET_ADDRESS VARCHAR(120), 
CITY VARCHAR(50) NOT NULL,
ZIPCODE VARCHAR(10) NOT NULL,
GENDER VARCHAR(30) CONSTRAINT GENDER_RECIPIENT_CHECK CHECK(GENDER IN ('MALE','FEMALE','OTHER')) 
);

CREATE TABLE Audit_log( 
AUDIT_LOG_ID NUMBER CONSTRAINT AUDIT_LOG_PK PRIMARY KEY, 
LOG_DESCRIPTION VARCHAR(150) NOT NULL, 
OPERATION_TYPE VARCHAR(15),
RECIPIENT_ID NUMBER,
TIME_STAMP TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE HOSPITAL(
HOSPITAL_ID NUMBER CONSTRAINT HOSPITAL_PK PRIMARY KEY,
HOSPITAL_NAME VARCHAR(90) NOT NULL,
HOSPITAL_STREET_ADDRESS VARCHAR(120),
CITY VARCHAR(50) NOT NULL,
ZIPCODE VARCHAR(10) NOT NULL,
HOSPITAL_CONTACT NUMBER NOT NULL CONSTRAINT HOSPITAL_CONTACT_UNQ UNIQUE,
HOSPITAL_LICENSE_NUMBER VARCHAR(50) NOT NULL CONSTRAINT HOSPITAL_LICENSE_UNQ UNIQUE
);


CREATE TABLE VACCINE_DETAILS(
VACCINE_ID NUMBER CONSTRAINT VACCINE_ID_PK PRIMARY KEY,
VACCINE_NAME VARCHAR(120) NOT NULL,
VIAL_SIZE NUMBER CONSTRAINT VIAL_SIZE_CHECK CHECK(VIAL_SIZE IN (10, 20, 30)),
LOT_ID VARCHAR(20) NOT NULL CONSTRAINT LOT_ID_UNQ UNIQUE,
MANUFACTURED_DATE DATE NOT NULL,
EXPIRY_DATE DATE NOT NULL
);

CREATE TABLE MEDICAL_WORKER(
MEDICAL_WORKER_ID NUMBER CONSTRAINT MEDICAL_WORKER_PK PRIMARY KEY,
FIRST_NAME VARCHAR(90),
LAST_NAME VARCHAR(90),
CONTACT_NUMBER NUMBER NOT NULL CONSTRAINT CONTACT_MEDICAL_WORKER_UNQ UNIQUE,
STREET_ADDRESS VARCHAR(120),
CITY VARCHAR(50) NOT NULL,
ZIPCODE VARCHAR(10) NOT NULL,
GENDER VARCHAR(30) CONSTRAINT GENDER_MEDICAL_WORKER_CHECK CHECK(GENDER IN ('MALE','FEMALE','OTHER')),
EMAIL_ID VARCHAR(40),
HOSPITAL_ID NUMBER NOT NULL CONSTRAINT HOSPITAL_ID_FK REFERENCES HOSPITAL(HOSPITAL_ID) ON DELETE CASCADE
);

CREATE TABLE REGISTRATION( 
REGISTRATION_ID NUMBER CONSTRAINT REGISTRATION_PK PRIMARY KEY, 
RECIPIENT_ID NUMBER NOT NULL CONSTRAINT RECIPIENT_ID_FK REFERENCES RECIPIENT(RECIPIENT_ID) ON DELETE CASCADE, 
USERNAME VARCHAR(20) NOT NULL CONSTRAINT USERNAME_UNQ UNIQUE, 
PASS_WORD VARCHAR(50) NOT NULL, 
EMAIL_ID VARCHAR(50) NOT NULL, 
LAST_VACCINATION_DATE DATE, 
PAYMENT_TIMESTAMP TIMESTAMP NOT NULL, 
PAYMENT_AMOUNT NUMBER NOT NULL, 
TRANSACTION_ID VARCHAR(20) NOT NULL CONSTRAINT TRANSACTION_ID_UNQ UNIQUE, 
PAYMENT_TYPE VARCHAR(20) CONSTRAINT PAYMENT_TYPE_CHECK CHECK(PAYMENT_TYPE IN ('CARD','CASH')) 
);

CREATE TABLE VACCINE_RECORD( 
VACCINE_RECORD_ID NUMBER CONSTRAINT VACCINE_RECORD_PK PRIMARY KEY, 
START_TIME TIMESTAMP NOT NULL, 
END_TIME TIMESTAMP NOT NULL, 
VACCINE_RECORD_DATE DATE DEFAULT SYSDATE, 
REMARKS VARCHAR(150), 
MEDICAL_WORKER_ID NUMBER NOT NULL CONSTRAINT MEDICAL_WORKER_ID_FK REFERENCES MEDICAL_WORKER(MEDICAL_WORKER_ID) ON DELETE CASCADE, 
REGISTRATION_ID NUMBER NOT NULL CONSTRAINT REGISTRATION_ID_FK REFERENCES REGISTRATION(REGISTRATION_ID) ON DELETE CASCADE, 
VACCINE_ID NUMBER NOT NULL CONSTRAINT VACCINE_ID_FK REFERENCES VACCINE_DETAILS(VACCINE_ID) ON DELETE CASCADE 
);

GRANT SELECT,INSERT, DELETE, UPDATE ON REGISTRATION TO RECIPIENT;
GRANT SELECT ON VACCINE_RECORD TO RECIPIENT;

GRANT SELECT, INSERT, UPDATE, DELETE ON MEDICAL_WORKER TO HOSPITAL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON VACCINE_RECORD TO HOSPITAL_ADMIN;
GRANT SELECT ON VACCINE_DETAILS TO HOSPITAL_ADMIN;
GRANT SELECT ON VACCINE_RECORD TO HOSPITAL_ADMIN;
GRANT SELECT ON REGISTRATION TO HOSPITAL_ADMIN;

GRANT SELECT, INSERT, UPDATE ON VACCINE_RECORD TO MEDICAL_WORKER;
GRANT SELECT ON VACCINE_DETAILS TO MEDICAL_WORKER;
GRANT SELECT ON REGISTRATION TO MEDICAL_WORKER;

--RECIPIENT BY APP_ADMIN
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(101,'ALLEN','SMITH','23-OCT-1997',6172344342,'234 HUNTINGTON AVE','BOSTON','02115','MALE');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(102,'AVA','CHEN','07-MAR-1990',8769971678,'3760 ARCHER ROAD','MATTAPAN','02124','FEMALE');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(103,'JAMES','MCMILLAN','12-JUL-1970',4123478001,'1667 K STREET','WASHINGTON DC','20006','OTHER');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(104,'RAKSHA','SHETTY','30-OCT-1995',8577990915,'682 PARKER SREET','BOSTON','02120','FEMALE');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(105,'ELLA','GLENN','20-MAR-2000',4132344890,'1255 RARITAN ROAD','CLARK','07066','OTHER');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(106,'RAHMAN','AHMAD','30-NOV-1960',3134500761,'1515 CLAY STREET','LOS ANGELES','94612','MALE');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(107,'GRAYSON','HARPER','14-AUG-1990',6167890915,'66 SPARKS STREET','CAMBRIDGE','02163','MALE');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(108,'SANIA','MEADOWS','06-APR-1998',7173124098,'3014 WEST COLUMBUS AVE','CHICAGO','60652','OTHER');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(109,'LILY','CALLOWAY','28-MAY-1996',8179708654,'3100 NEWPORT AVE','NEWPORT BEACH','92660','FEMALE');
INSERT INTO RECIPIENT(RECIPIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,CONTACT_NUMBER,STREET_ADDRESS,CITY,ZIPCODE,GENDER)
VALUES(110,'STELLA','ALONSO','16-FEB-1997',9180675421,'235TH SOUTHEAST STREET','KENT','98031','FEMALE');


--HOSPITAL BY APP ADMIN
INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1101,'MASS BRIGHAM GENERAL HOSPITAL','243 CHARLES STREET','BOSTON','02114',4146772234,'ACH12345HOSP');
INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1102,'ILLINOIS GENERAL HOSPITAL','1310 COMMONS DRIVE','CHICAGO','60134',3124433567,'ILL3425HOSP');
INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1103,'SOUTHERN CALIFORNIA HOSPITAL','6245 DE LONGPRE AVE','LOS ANGELES','90015',6167090808,'LAG2908HOSP');
INSERT INTO HOSPITAL (HOSPITAL_ID,HOSPITAL_NAME,HOSPITAL_STREET_ADDRESS,CITY,ZIPCODE,HOSPITAL_CONTACT,HOSPITAL_LICENSE_NUMBER) 
VALUES 
(1104,'GWU HOSPITAL','900 23RD STREET','WASHINGTON DC','20037',7178907070,'WAS7178HOSP');

--VACCINE_DETAILS- By APP ADMIN
 
INSERT INTO VACCINE_DETAILS (VACCINE_ID,VACCINE_NAME,VIAL_SIZE,LOT_ID,MANUFACTURED_DATE,EXPIRY_DATE) 
VALUES(301,'JJ',20,'LOT6798','08-AUG-2021','06-NOV-2023');

INSERT INTO VACCINE_DETAILS (VACCINE_ID,VACCINE_NAME,VIAL_SIZE,LOT_ID,MANUFACTURED_DATE,EXPIRY_DATE) 
VALUES(302,'MODERNA',10,'LOT4567','07-JUN-2022','05-SEP-2023');
 
INSERT INTO VACCINE_DETAILS (VACCINE_ID,VACCINE_NAME,VIAL_SIZE,LOT_ID,MANUFACTURED_DATE,EXPIRY_DATE) 
VALUES(303,'PFIZER',30,'LOT1234','21-NOV-2021','19-AUG-2023');

INSERT INTO VACCINE_DETAILS (VACCINE_ID,VACCINE_NAME,VIAL_SIZE,LOT_ID,MANUFACTURED_DATE,EXPIRY_DATE) 
VALUES(304,'NOVAVAX',10,'LOT5123','17-JAN-2022','06-FEB-2022');

--SELECT * FROM RECIPIENT;
--SELECT * FROM HOSPITAL;
--SELECT * FROM VACCINE_DETAILS;
--SELECT * FROM MEDICAL_WORKER;
--SELECT * FROM registration;
--SELECT * FROM vaccine_record;